Update tmux-start to set TERM to screen-256color

diff --git a/bin/tmux-start b/bin/tmux-start
--- a/bin/tmux-start
+++ b/bin/tmux-start
@@ -5,10 +5,18 @@ set -x
 # Connects to an existing "main" session if we have one, otherwise makes a new sesion
 TMUX_MAIN_SESSION="main"
 
+if ! command -v tmux &> /dev/null; then
+    echo "tmux not installed? Couldn't find it." >&2
+    exit 1
+fi
+
 if [[ "${TERM}" =~ "screen".* ]]; then
     echo "Already in tmux like session" >&2
     exit 1
-fi 
+fi
+
+# Work around for remote servers not having tmux-256color yet
+export TERM="screen-256color"
 
 SESSION_STATUS=$(tmux list-sessions | grep "${TMUX_MAIN_SESSION}")
 if [[ ! -z "${SESSION_STATUS}" ]]; then
