Fix up docker-imageremote and let user pick fuzzy match using fzf

diff --git a/docker/cli-plugins/docker-imageremote b/docker/cli-plugins/docker-imageremote
--- a/docker/cli-plugins/docker-imageremote
+++ b/docker/cli-plugins/docker-imageremote
@@ -36,12 +36,28 @@ function main() {
     authorization_header="Authorization: Bearer $token"
     tag_list_url="https://hub.docker.com/v2/repositories/$image_name/tags?page_size=10000"
     curl --silent --get -H "Accept: application/json" -H "$authorization_header" "$tag_list_url" | jq -e --raw-output '.results[].name'
-    if [[ $? != 0 ]]; then
+    if [[ $? != 0 ]] && [ -t 0 ] ; then
+        # Couldn't find that repo, let's try searching and letting the user choose the correct name
+
         echo "No repos by that name found, searching for repos..." >&2
         repo_namespace="$(echo "$image_name" | cut -d "/" -f1)"
         repo_name="$(echo "$image_name" | cut -d "/" -f2)"
         repo_list_url="https://hub.docker.com/v2/repositories/${repo_namespace}/?page_size=10000"
-        curl --silent --get -H "Accept: application/json" -H "$authorization_header" "$repo_list_url" | jq --raw-output '.results[].name' | grep -E "^${repo_name}"
+        
+        repos="$(curl --silent --get -H "Accept: application/json" -H "$authorization_header" "$repo_list_url" | jq --raw-output '.results[].name' | grep -E "^${repo_name}")"
+        
+        if command -v fzf &>/dev/null; then
+            chosen_repo="$(echo "$repos" | fzf)"
+            if [[ $? == 0 ]]; then
+                main "$repo_namespace/$chosen_repo"
+            else
+                echo "Choosing failed, stopping" >&2
+                exit 1
+            fi
+        else
+            echo "No repos by that name found, found these that were similar:\n ${repos}">&2
+            exit 1
+        fi
     fi
 }
 
